"""Triangle quadrature for the BB element (Aeris BB Phase 2).

STANDALONE, pure stdlib, no numpy. Provides a quadrature rule on the
reference triangle T_ref = {(xi1,xi2): xi1>=0, xi2>=0, xi1+xi2<=1}
(area 1/2), plus a "domain iterator" that maps the reference rule onto
an arbitrary triangle.

## Choice of rule — collapsed (Duffy) Gauss-Legendre, NOT Xiao-Gimbutas

Ludwig (2018) adopts minimal SYMMETRIC rules (Xiao-Gimbutas). Those are
the product of a nonlinear moment-matching optimisation; their nodes
cannot be reconstructed by hand to working precision, and a mis-typed
digit would fail the monomial test with no oracle to repair it. So we
use the collapsed-coordinate (Duffy) construction over HARD-CODED 1D
Gauss-Legendre tables instead. That rule satisfies every hard
requirement and is verifiable from first principles:

  * positive weights      (Gauss-Legendre weights are positive; products
                           of positives stay positive)
  * strictly interior     (GL nodes lie in the open interval; the Duffy
                           map sends them into the open triangle)
  * exact to total degree 2(p-1)  (proven by the monomial test)
  * NOT generated by optimisation — only the standard 1D GL table, which
    cross-checks against closed forms (n<=3) and the monomial test
  * ports verbatim to C++ (the 1D table is the same literal constants)

Trade-off vs Xiao-Gimbutas: more points (n^2 vs the symmetric minimum)
and no S3 symmetry. Both are point-count / symmetry concerns, not
correctness. Dropping Ludwig's symmetric tables in later is a same-
interface swap gated by this module's monomial test.

## Duffy map

Square (u,v) in [0,1]^2 -> T_ref:  xi1 = u*(1-v),  xi2 = v,  |J| = (1-v).
  integral_Tref f dxi = integral_[0,1]^2 f(u(1-v), v) (1-v) du dv.
With n GL points per direction the integrand is degree (a) in u and
(a+b+1) in v for a monomial xi1^a xi2^b of total degree d=a+b, so n GL
points integrate exactly up to total degree 2n-2 (the v-direction, with
the extra Jacobian power, is the binding one). Hence for a target degree
D we take n = ceil((D+2)/2).

## Degree to request

For the KL shell STIFFNESS the membrane-binding exactness is 2(p-1).
The KL integrand is NON-polynomial even on flat elements (the sqrt in
the normal normalisation ||a3||), so monomial exactness is the rule's
unit test, NOT the physical acceptance criterion — that is "integration
error dominated by discretisation error" and only shows in the Phase-3
convergence study. Start at 2(p-1); the one-degree-higher rule is the
lever if a Phase-3 integration-error plateau ever appears. A consistent
MASS matrix would separately want 2p (not needed for stiffness).
"""
from __future__ import annotations

from math import ceil, factorial

# ---------------------------------------------------------------------------
# Hard-coded 1D Gauss-Legendre tables on [-1, 1] (nodes, weights), 16 digits.
# Standard textbook values; verifiable against closed forms for n<=3
# (n=2: +-1/sqrt(3), w=1; n=3: 0 & +-sqrt(3/5), w=8/9 & 5/9) and against
# the monomial exactness test for all n. Port these verbatim to C++.
# ---------------------------------------------------------------------------
_GL = {
    1: ([0.0],
        [2.0]),
    2: ([-0.5773502691896257, 0.5773502691896257],
        [1.0, 1.0]),
    3: ([-0.7745966692414834, 0.0, 0.7745966692414834],
        [0.5555555555555556, 0.8888888888888888, 0.5555555555555556]),
    4: ([-0.8611363115940526, -0.3399810435848563,
         0.3399810435848563, 0.8611363115940526],
        [0.3478548451374538, 0.6521451548625461,
         0.6521451548625461, 0.3478548451374538]),
    5: ([-0.9061798459386640, -0.5384693101056831, 0.0,
         0.5384693101056831, 0.9061798459386640],
        [0.2369268850561891, 0.4786286704993665, 0.5688888888888889,
         0.4786286704993665, 0.2369268850561891]),
    6: ([-0.9324695142031521, -0.6612093864662645, -0.2386191860831969,
         0.2386191860831969, 0.6612093864662645, 0.9324695142031521],
        [0.1713244923791704, 0.3607615730481386, 0.4679139345726910,
         0.4679139345726910, 0.3607615730481386, 0.1713244923791704]),
    7: ([-0.9491079123427585, -0.7415311855993945, -0.4058451513773972,
         0.0, 0.4058451513773972, 0.7415311855993945, 0.9491079123427585],
        [0.1294849661688697, 0.2797053914892766, 0.3818300505051189,
         0.4179591836734694, 0.3818300505051189, 0.2797053914892766,
         0.1294849661688697]),
    8: ([-0.9602898564975363, -0.7966664774136267, -0.5255324099163290,
         -0.1834346424956498, 0.1834346424956498, 0.5255324099163290,
         0.7966664774136267, 0.9602898564975363],
        [0.1012285362903763, 0.2223810344533745, 0.3137066458778873,
         0.3626837833783620, 0.3626837833783620, 0.3137066458778873,
         0.2223810344533745, 0.1012285362903763]),
}
_MAX_N = max(_GL)


def gauss_legendre_unit(n: int) -> tuple[list[float], list[float]]:
    """n-point Gauss-Legendre nodes/weights mapped to [0,1]
    (x' = (x+1)/2, w' = w/2). Exact for 1D polynomials up to degree 2n-1.
    sum(weights) == 1."""
    if n not in _GL:
        raise ValueError(f"no hard-coded GL table for n={n} (have 1..{_MAX_N})")
    nodes, weights = _GL[n]
    return ([0.5 * (x + 1.0) for x in nodes],
            [0.5 * w for w in weights])


def points_for_degree(degree: int) -> int:
    """1D point count n per direction so the Duffy rule is exact to the
    given TOTAL polynomial degree on the triangle."""
    if degree < 0:
        raise ValueError("degree must be >= 0")
    return max(1, ceil((degree + 2) / 2))


def quad_triangle(degree: int) -> list[tuple[float, float, float]]:
    """Reference-triangle quadrature exact to total polynomial `degree`.
    Returns [(xi1, xi2, weight), ...] with all weights > 0, all points
    strictly interior, and sum(weight) == area(T_ref) == 1/2."""
    n = points_for_degree(degree)
    if n > _MAX_N:
        raise ValueError(
            f"degree {degree} needs n={n} GL points; hard-coded table stops "
            f"at n={_MAX_N} (total degree {2 * _MAX_N - 2}). Add a 1D table.")
    u_nodes, u_w = gauss_legendre_unit(n)
    v_nodes, v_w = gauss_legendre_unit(n)
    pts = []
    for v, wv in zip(v_nodes, v_w):
        jac = 1.0 - v
        for u, wu in zip(u_nodes, u_w):
            xi1 = u * (1.0 - v)
            xi2 = v
            pts.append((xi1, xi2, wu * wv * jac))
    return pts


# ---------------------------------------------------------------------------
# Domain iterator: map the reference rule onto an arbitrary triangle.
# ---------------------------------------------------------------------------

def triangle_area(p0, p1, p2) -> float:
    """Unsigned area of the triangle (p0,p1,p2), points in R^2 or R^3."""
    a = [p1[i] - p0[i] for i in range(len(p0))]
    b = [p2[i] - p0[i] for i in range(len(p0))]
    if len(p0) == 2:
        cross = a[0] * b[1] - a[1] * b[0]
        return 0.5 * abs(cross)
    cx = a[1] * b[2] - a[2] * b[1]
    cy = a[2] * b[0] - a[0] * b[2]
    cz = a[0] * b[1] - a[1] * b[0]
    return 0.5 * (cx * cx + cy * cy + cz * cz) ** 0.5


def map_rule_to_triangle(p0, p1, p2, degree: int):
    """Affine-map the reference rule onto triangle (p0,p1,p2).

    Yields (point, weight) where point = p0 + xi1*(p1-p0) + xi2*(p2-p0)
    (in the embedding dimension of the vertices) and the weights scale by
    |det J| = 2*area, so sum(weight) == area(triangle) and the rule
    integrates polynomials of total degree `degree` (in the barycentric
    parametrisation) exactly. This is the standalone stand-in for the
    G+Smo makeDomainIterator contract, which is only validated against
    the assembler in Phase 3 — here it is checked against hand
    calculation only."""
    area = triangle_area(p0, p1, p2)
    scale = 2.0 * area                      # |det J| of ref(area 1/2)->target
    dim = len(p0)
    for (xi1, xi2, w) in quad_triangle(degree):
        pt = tuple(p0[i] + xi1 * (p1[i] - p0[i]) + xi2 * (p2[i] - p0[i])
                   for i in range(dim))
        yield pt, w * scale


# ---------------------------------------------------------------------------
# Exact reference integral of a monomial over T_ref (for the test module).
# ---------------------------------------------------------------------------

def monomial_integral_ref(a: int, b: int) -> float:
    """integral over T_ref of xi1^a xi2^b dxi = a! b! / (a+b+2)!."""
    return factorial(a) * factorial(b) / factorial(a + b + 2)
